import {estimateTime,summarize,counts,category,permissionText,explain} from './ui-logic.js';
import {AdaptiveScheduler} from './scheduler.js';
import {getRules,updateRules} from './rule-store.js';
import {reputation,clearReputation} from './reputation.js';
import {benchmark} from './benchmark.js';
const VERSION='3.1.0',$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>{if(!n)return '0 Б';const k=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return `${(n/1024**k).toLocaleString('ru-RU',{maximumFractionDigits:1})} ${['Б','КиБ','МиБ','ГиБ','ТиБ'][k]}`};
let db,reports=[],database=[],queue=[],batch=[],currentReport,installPrompt,settings={theme:'auto',accent:'jade',density:'comfortable',retention:'0'},filter='all',search='',dateFilter='',canceling=false;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6000)}
const storageReady=new Promise(resolve=>{try{const r=indexedDB.open('anti-wiew',1);r.onupgradeneeded=()=>{r.result.createObjectStore('reports',{keyPath:'id'});r.result.createObjectStore('settings')};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>{toast('История недоступна. Скачайте нужные отчёты перед закрытием.');resolve()};r.onblocked=()=>toast('Закройте другие вкладки Anti-wiew для открытия истории')}catch{resolve()}});
async function read(store,key){await storageReady;if(!db)return key?undefined:[];return new Promise(resolve=>{try{const r=key?db.transaction(store).objectStore(store).get(key):db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(key?undefined:[])}catch{resolve(key?undefined:[])}})}
async function write(store,value,key,remove=false){await storageReady;if(!db)throw Error('Нет хранилища');return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite'),s=tx.objectStore(store);if(remove)s.delete(key);else if(key)s.put(value,key);else s.put(value);tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error||Error('Запись отменена'))})}
function applySettings(){document.body.classList.toggle('light',settings.theme==='light'||settings.theme==='auto'&&matchMedia('(prefers-color-scheme: light)').matches);document.body.dataset.accent=settings.accent;document.body.classList.toggle('compact',settings.density==='compact');for(const k of ['theme','accent','density','retention'])$('#'+k+'Select').value=settings[k]}
async function setSetting(k,v){settings[k]=v;applySettings();try{await write('settings',v,k);if(k==='retention')await pruneHistory()}catch{toast('Настройка применена, но не сохранена')}}
$('#theme').onclick=()=>setSetting('theme',document.body.classList.contains('light')?'dark':'light');for(const k of ['theme','accent','density','retention'])$('#'+k+'Select').onchange=e=>setSetting(k,e.target.value);matchMedia('(prefers-color-scheme: light)').addEventListener('change',applySettings);
function tab(name){document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#crumb').textContent={scan:'ПРОВЕРКА',reports:'ОТЧЁТЫ',settings:'НАСТРОЙКИ'}[name];if(name==='reports')renderReports();if(name==='settings'){renderDeletion();storageInfo()}}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
const scheduler=new AdaptiveScheduler(pump,renderProgress,{cap:1});
function renderProgress(){const jobs=[...scheduler.jobs.values()];$('#eta').textContent=estimateTime(jobs,queue);$('#parallelInfo').textContent=`Активно ${jobs.length} · лимит ${scheduler.limit}`;const total=batch.reduce((n,x)=>n+x.size,0),done=batch.reduce((n,x)=>n+(x.state==='done'?x.size:x.done||0),0),finished=batch.length&&!batch.some(x=>['waiting','running'].includes(x.state));const pct=total?Math.min(finished?100:99,Math.floor(done/total*100)):finished?100:0;$('#ring').style.setProperty('--progress',pct+'%');$('#percent').textContent=pct+'%';$('#ring').setAttribute('aria-valuenow',pct);$('#queued').textContent=queue.filter(x=>['waiting','running'].includes(x.state)).length;$('#checked').textContent=queue.filter(x=>x.state==='done').length;$('#alerts').textContent=queue.filter(x=>x.report?.findings.length).length;$('#cancel').disabled=!queue.some(x=>['waiting','running'].includes(x.state));for(const x of jobs){const row=document.getElementById('q-'+x.id);if(row){row.querySelector('progress').value=x.done;row.querySelector('.file-percent').textContent=x.phase&&x.phase!=='hash'?'…':Math.min(99,Math.floor((x.done||0)/Math.max(1,x.size)*100))+'%';row.querySelector('.live').textContent=x.phase==='reputation'?'Репутация SHA-256 · ожидаем ответ сервиса':x.phase==='yara'?'Сигнатурный анализ YARA':x.phase==='static'?'Разбор структуры файла':x.phase==='archive'?`Архив: ${x.archiveScanned||0} / ${x.archiveTotal||'?'} · ${x.archiveName||'Читаем каталог'}`:`${bytes(x.done)} / ${bytes(x.size)} · ${x.rate?bytes(x.rate)+'/с':'Оцениваем скорость'}`}}}
const labels={clear:'Без находок',findings:'Есть находки',partial:'Проверка ограничена'};
function renderQueue(){$('#queueBadge').textContent=queue.length;$('#queue').innerHTML=queue.length?queue.map(x=>`<div class="row" id="q-${x.id}"><div class="row-top"><span class="filename">${esc(x.name)}</span><span class="status ${x.report?category(x.report):''}">${esc(x.label)}</span></div><div class="meta">${bytes(x.size)}</div>${x.state==='running'?`<progress max="${x.size||1}" value="${x.done||0}"></progress><div class="file-progress-meta"><span class="meta live"></span><span class="file-percent">0%</span></div>`:''}${x.report?`<button class="report-open" data-report="${x.id}">Открыть отчёт ↗</button>`:''}</div>`).join(''):'<div class="empty">Очередь пуста<span>Добавьте файлы — анализ начнётся автоматически.</span></div>';renderProgress()}
async function addFiles(files){const selected=Array.from(files);await initialized;if(!selected.length)return;if(!queue.some(x=>['waiting','running'].includes(x.state))){batch=[];$('#summary').hidden=true;}for(const file of selected){const rulePack=await getRules().catch(()=>null);const x={rulePack,cloud:$('#vtEnabled').checked&&(!!$('#vtKey').value.trim()||!!$('#bazaarKey').value.trim()),id:crypto.randomUUID(),file,name:file.name,size:file.size,state:'waiting',label:'В очереди',done:0,database};queue.push(x);batch.push(x)}renderQueue();pump()}
function pump(){if(canceling)return;while(scheduler.jobs.size<scheduler.limit){const x=queue.find(x=>x.state==='waiting');if(!x)break;start(x)}}
function start(x){x.state='running';x.label='Проверяется';scheduler.jobs.set(x.id,x);renderQueue();try{x.worker=new Worker('./worker.js',{type:'module'});x.worker.onmessage=async({data:d})=>{if(x.state!=='running')return;if(d.kind==='hash-ready'){const value=await reputation(d.sha256,{vt:$('#vtKey').value.trim(),bazaar:$('#bazaarKey').value.trim()},()=>x.state==='running'&&$('#vtEnabled').checked);if(x.state==='running')x.worker.postMessage({kind:'reputation',value});return}else if(d.kind==='alert'){x.label=d.text;toast(d.text);renderQueue();return}else if(d.kind==='progress'){x.rate=d.seconds>0?d.done/d.seconds:0;Object.assign(x,d);renderProgress()}else if(d.kind==='done')finish(x,d.report);else failure(x,d.error,d.done)};x.worker.onerror=e=>failure(x,e.message||'Ошибка рабочего потока',x.done);x.worker.postMessage({file:x.file,id:x.id,database:x.database,rulePack:x.rulePack,cloud:x.cloud})}catch(e){failure(x,e.message,x.done)}}
async function finish(x,r){if(x.state!=='running')return;x.worker?.terminate();x.state=r.coverage==='Неполная проверка'?'error':'done';x.report=r;x.label=labels[category(r)];x.done=r.bytesRead;x.file=null;x.database=null;x.rulePack=null;scheduler.jobs.delete(x.id);reports.unshift(r);renderQueue();renderReports();try{await write('reports',r)}catch{toast('Отчёт не сохранён. Скачайте JSON до закрытия вкладки.')}pump();if(!canceling&&!queue.some(x=>['waiting','running'].includes(x.state)))showSummary()}
function failure(x,error,done){finish(x,{id:x.id,name:x.name,size:x.size,bytesRead:done||0,created:new Date().toISOString(),status:'Проверить полностью не удалось',engine:'AW-2.0',coverage:'Неполная проверка',partial:true,findings:[],limitations:[error],log:['Проверка прервана']})}
$('#choose').onclick=()=>$('#files').click();$('#files').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')};$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');$('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('drag');addFiles(e.dataTransfer.files)};
$('#cancel').onclick=async()=>{canceling=true;const pending=[];for(const x of queue){if(x.state==='waiting'){x.state='running';pending.push(finish(x,{id:x.id,name:x.name,size:x.size,bytesRead:0,created:new Date().toISOString(),status:'Отменено',engine:'AW-2.0',coverage:'Неполная проверка',partial:true,findings:[],limitations:['Отменено до начала проверки'],log:[]}))}else if(x.state==='running'){x.worker?.terminate();pending.push(finish(x,{id:x.id,name:x.name,size:x.size,bytesRead:x.done||0,created:new Date().toISOString(),status:'Отменено',engine:'AW-2.0',coverage:'Неполная проверка',partial:true,findings:[],limitations:['Отменено пользователем'],log:[]}))}}await Promise.all(pending);canceling=false;renderQueue();showSummary()};
let summaryShown='';function showSummary(){const key=batch.map(x=>x.id).join(',');if(!batch.length||summaryShown===key)return;summaryShown=key;const r=summarize(batch),c=counts(batch);$('#summaryTitle').textContent=r.title;$('#summaryText').textContent=r.text;$('#summaryCount').innerHTML=Object.entries(c).map(([k,v])=>`<button class="summary-stat ${k}" data-filter="${k}"><b>${v}</b>${labels[k]}</button>`).join('');$('#summary').hidden=false}
$('#closeSummary').onclick=()=>($('#summary').hidden=true);$('#summaryReports').onclick=()=>{($('#summary').hidden=true);filter='all';$('#reportFilter').value=filter;tab('reports')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;$('#reportFilter').value=filter;($('#summary').hidden=true);tab('reports')}const id=e.target.closest('[data-report]')?.dataset.report;if(id)openReport(id)});
$('#reportSearch').oninput=e=>{search=e.target.value.toLowerCase();renderReports()};$('#reportFilter').onchange=e=>{filter=e.target.value;renderReports()};$('#reportDate').onchange=e=>{dateFilter=e.target.value;renderReports()};
function renderReports(){$('#count').textContent=reports.length;const filtered=reports.filter(r=>r.name.toLowerCase().includes(search)&&(filter==='all'||category(r)===filter)&&(!dateFilter||localDate(r.created)===dateFilter));$('#reportList').innerHTML=filtered.length?filtered.map(r=>`<div class="row"><div class="row-top"><span class="filename">${esc(r.name)}</span><button class="report-open" data-report="${r.id}">Отчёт ↗</button></div><div class="status ${category(r)}">${labels[category(r)]}</div><div class="meta">${new Date(r.created).toLocaleString('ru-RU')} · ${bytes(r.size)}</div></div>`).join(''):'<div class="empty">Нет отчётов по выбранным условиям.</div>'}
function localDate(s){const d=new Date(s);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function openReport(id){currentReport=reports.find(r=>r.id===id)||queue.find(x=>x.id===id)?.report;if(!currentReport)return;const r=currentReport,c=category(r);$('#detailBody').innerHTML=`<p class="filename">${esc(r.name)}</p><p class="status ${c}">${labels[c]}</p><p>${c==='clear'?'Доступные правила не нашли совпадений. Это не гарантия безопасности.':c==='partial'?'Часть анализа выполнить не удалось. Причины указаны ниже.':'Посмотрите объяснения находок перед открытием файла.'}</p>${r.findings.map(f=>`<div class="finding"><b>${esc(f.title)}</b>${f.path?`<p>${esc(f.path)}</p>`:''}<p>${explain(f)}</p></div>`).join('')}${r.apk?`<h2>Об APK</h2><dl>${Object.entries({'Пакет':r.apk.package,'Версия':r.apk.versionName,'Код версии':r.apk.versionCode,'Минимальный SDK':r.apk.minSdk,'Целевой SDK':r.apk.targetSdk}).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v||'Не указан')}</dd>`).join('')}</dl><h2>Разрешения (${r.apk.permissions.length})</h2><p>Разрешения сами по себе не доказывают наличие вируса.</p>${r.apk.permissions.map(p=>`<p><b>${permissionText(p)}</b><br><small>${esc(p)}</small></p>`).join('')}`:''}<details><summary>Технические подробности</summary><dl>${Object.entries({'Дата':new Date(r.created).toLocaleString('ru-RU'),'Размер':bytes(r.size),'Прочитано':bytes(r.bytesRead),'Формат':r.type||'Не определён','SHA-256':r.sha256||'Не вычислен','Длительность':r.durationMs===undefined?'Не завершена':r.durationMs+' мс','Движок':r.engine,'Хеш-база':(r.databaseEntries||0)+' записей','YARA-база':r.ruleVersion||'Нет','Набор правил':r.ruleDescription||'Нет'}).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${r.archive?`<h2>Содержимое ZIP</h2><p>Проверено: ${r.archive.scanned}. Пропущено: ${r.archive.skipped}. Распаковано: ${bytes(r.archive.expandedBytes)}.</p>${r.archive.entries.map(x=>`<p>${esc(x.name)}<br><small>${x.status==='scanned'?'Прочитан и проверен':'Пропущен'} ${esc(x.reason||'')}<br>${esc(x.sha256||'')}</small></p>`).join('')}`:''}<h2>YARA и репутация</h2><pre>${esc(JSON.stringify({yara:r.yara,reputation:r.reputation},null,2))}</pre><h2>Структура файла</h2><pre>${esc(JSON.stringify(r.analysis,null,2))}</pre><h2>Находки</h2><pre>${esc(JSON.stringify(r.findings,null,2))}</pre>${r.archive?`<h2>Анализ файлов архива</h2><pre>${esc(JSON.stringify(r.archive.entries.map(e=>({name:e.name,analysis:e.analysis,archive:e.archive})),null,2))}</pre>`:''}<h2>Журнал</h2><pre>${esc((r.log||[]).join('\n'))}</pre></details><h2>Ограничения</h2><ul>${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;if(!$('#detail').open)$('#detail').showModal()}
$('#closeDetail').onclick=()=>$('#detail').close();function download(value,name){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}$('#exportReport').onclick=()=>download(currentReport,'anti-wiew-'+currentReport.id+'.json');$('#exportHistory').onclick=()=>download({version:VERSION,exported:new Date().toISOString(),reports},'anti-wiew-history.json');
function renderDeletion(){$('#deleteList').innerHTML=reports.map(r=>`<label class="delete-row"><span>${esc(r.name)}<br><small>${new Date(r.created).toLocaleString('ru-RU')}</small></span><input type="checkbox" value="${r.id}" aria-label="Удалить ${esc(r.name)}"></label>`).join('')||'<p>Нет сохранённых отчётов.</p>'}
async function removeReports(ids){for(const id of ids){await write('reports',null,id,true);reports=reports.filter(r=>r.id!==id);const x=queue.find(x=>x.id===id);if(x)x.report=null}renderReports();renderDeletion();renderQueue();storageInfo()}
$('#deleteSelected').onclick=async()=>{const ids=[...document.querySelectorAll('#deleteList input:checked')].map(x=>x.value);if(!ids.length)return toast('Выберите отчёты');if(!confirm(`Удалить отчёты (${ids.length})?`))return;try{await removeReports(ids);toast('Отчёты удалены')}catch{toast('Не удалось удалить все отчёты')}};
async function pruneHistory(){const days=Number(settings.retention);if(days)await removeReports(reports.filter(r=>Date.parse(r.created)<Date.now()-days*86400000).map(r=>r.id))}
async function storageInfo(){const size=new Blob([JSON.stringify(reports)]).size;let text=`Отчёты (JSON): ${bytes(size)}. `;try{const s=await navigator.storage.estimate();text+=`Всего данных сайта: ${bytes(s.usage)} (включая офлайн-кеш).`}catch{}$('#storageInfo').textContent=text}
$('#importDb').onclick=()=>$('#dbFile').click();$('#dbFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>20*1024*1024)return toast('Максимальный размер базы — 20 МиБ');try{const data=JSON.parse(await file.text());if(!Array.isArray(data)||data.length>100000||data.some(x=>!x||typeof x.sha256!=='string'||!/^[a-f0-9]{64}$/i.test(x.sha256)||typeof x.name!=='string'||!x.name.length||x.name.length>200))throw Error('Ожидаются записи {sha256, name}');const clean=[...new Map(data.map(x=>[x.sha256.toLowerCase(),{sha256:x.sha256.toLowerCase(),name:x.name}])).values()];await write('settings',clean,'database');database=clean;$('#dbInfo').textContent='Записей: '+database.length;toast('База импортирована')}catch(e){toast(e.message)}};$('#clearDb').onclick=async()=>{try{await write('settings',[],'database');database=[];$('#dbInfo').textContent='Записей: 0'}catch{toast('Не удалось удалить базу')}};
$('#selfTest').onclick=()=>{const text=['X5O!P%@AP[4\\PZX54(P^)7CC)7}$','EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'].join('');addFiles([new File([text],'anti-wiew-eicar-test.txt',{type:'text/plain'})]);tab('scan');toast('Добавлен безвредный тест EICAR. Ожидаемый результат — обнаружение теста.')};
$('#installedVersion').textContent=VERSION;$('#checkUpdates').onclick=async()=>{const b=$('#checkUpdates');b.disabled=true;$('#updateStatus').textContent='Проверяем…';$('#applyUpdate').hidden=true;try{const response=await fetch('./version.json',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const v=await response.json();if(!/^\d+\.\d+\.\d+$/.test(v.version)||!Array.isArray(v.changes)||v.changes.some(x=>typeof x!=='string'))throw Error();$('#updateStatus').textContent=v.version===VERSION?'Установлена актуальная версия '+VERSION:'Доступна версия '+v.version;$('#changes').replaceChildren(...v.changes.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('#applyUpdate').hidden=v.version===VERSION;if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();await reg?.update()}}catch{$('#updateStatus').textContent='Не удалось проверить обновления. Нужен интернет.'}finally{b.disabled=false}};
$('#applyUpdate').onclick=async()=>{if(scheduler.jobs.size)return toast('Дождитесь завершения проверки');const reg=await navigator.serviceWorker?.getRegistration();if(reg?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage({type:'ACTIVATE'})}else location.reload()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').disabled=false;$('#installInfo').textContent='Можно установить приложение на главный экран.'});$('#installApp').onclick=async()=>{if(!installPrompt)return toast('Откройте меню браузера → «Установить приложение» или «На главный экран».');await installPrompt.prompt();installPrompt=null};
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('#offlineInfo').textContent='Офлайн-файлы сохранены. После первого открытия приложение доступно без сети.';reg.addEventListener('updatefound',()=>{$('#updateStatus').textContent='Загружается новая офлайн-версия. Нажмите «Проверить обновления».'})}).catch(()=>$('#offlineInfo').textContent='Офлайн-режим недоступен в этом браузере.')}
window.addEventListener('beforeunload',e=>{if(scheduler.jobs.size){e.preventDefault();e.returnValue=''}});
const initialized=(async()=>{await storageReady;reports=(await read('reports')).sort((a,b)=>b.created.localeCompare(a.created));database=await read('settings','database')||[];for(const k of Object.keys(settings))settings[k]=await read('settings',k)||settings[k];applySettings();await pruneHistory().catch(()=>toast('Не удалось очистить старые отчёты'));$('#dbInfo').textContent='Записей: '+database.length;renderReports();renderDeletion();storageInfo()})();applySettings();renderQueue();

$('#parallelSelect').onchange=e=>{scheduler.setMode(e.target.value);renderProgress();pump()};

function rulesInfo(pack){$('#rulesInfo').textContent=pack?`База ${pack.manifest.version}. ${pack.manifest.description}`:'Правила пока недоступны. Подключитесь к сети и обновите базу.'}
let updatingRules=false;
async function refreshRules(){if(updatingRules||scheduler.jobs.size)return;updatingRules=true;$('#refreshRules').disabled=true;try{rulesInfo(await updateRules());$('#rulesChecked').textContent='Проверено: '+new Date().toLocaleString('ru-RU')}catch(e){$('#rulesChecked').textContent='Обновление не выполнено: '+e.message}finally{updatingRules=false;$('#refreshRules').disabled=false}}
$('#refreshRules').onclick=refreshRules;
getRules().then(rulesInfo).catch(()=>rulesInfo(null));
window.addEventListener('online',refreshRules);
setInterval(()=>{if(navigator.onLine&&!document.hidden)refreshRules()},6*3600000);
$('#vtEnabled').onchange=()=>{if($('#vtEnabled').checked&&!$('#vtKey').value.trim()&&!$('#bazaarKey').value.trim()){$('#vtEnabled').checked=false;toast('Введите ключ хотя бы одного сервиса')} };
$('#forgetVt').onclick=()=>{$('#vtEnabled').checked=false;$('#vtKey').value='';$('#bazaarKey').value='';toast('Ключ удалён из текущей сессии')};
$('#clearVtCache').onclick=async()=>{try{await clearReputation();toast('Кеш репутации очищен')}catch{toast('Не удалось очистить кеш')}};
async function calibrate(){if(scheduler.jobs.size)return toast('Дождитесь завершения проверки');$('#benchmarkInfo').textContent='Измеряем скорость SHA-256…';const result=await benchmark();scheduler.cap=result.cap;$('#benchmarkInfo').textContent=result.error?'Тест недоступен: используется один поток':`SHA-256: ${result.mbps.toFixed(1)} МиБ/с. Автоматический предел: ${result.cap}.`;if(!result.error)await write('settings',result,'benchmark').catch(()=>{});}
$('#calibrate').onclick=calibrate;
initialized.then(async()=>{const old=await read('settings','benchmark');if(old&&Date.now()-old.at<30*86400000){scheduler.cap=old.cap;$('#benchmarkInfo').textContent=`Последний замер: ${old.mbps.toFixed(1)} МиБ/с. Предел: ${old.cap}.`}else calibrate()});
