// Mach-O headers and load commands, based on Apple's mach-o/loader.h and fat.h.
export function parseMachO(b,depth=0){
 const d=new DataView(b.buffer,b.byteOffset,b.byteLength),need=(p,n)=>{if(!Number.isSafeInteger(p)||!Number.isSafeInteger(n)||p<0||n<0||p+n>b.length)throw Error('Mach-O: данные вне файла')};need(0,4);const magic=d.getUint32(0,false);
 const fat=[0xcafebabe,0xbebafeca,0xcafebabf,0xbfbafeca].includes(magic);
 if(fat){if(depth)throw Error('Mach-O: вложенный universal-контейнер');need(0,8);const le=magic===0xbebafeca||magic===0xbfbafeca,wide=magic===0xcafebabf||magic===0xbfbafeca,n=d.getUint32(4,le),step=wide?32:20;if(!n||n>32)throw Error('Mach-O: лимит архитектур');need(8,n*step);const architectures=[],ranges=[];for(let i=0;i<n;i++){const p=8+i*step,offset=wide?Number(d.getBigUint64(p+8,le)):d.getUint32(p+8,le),size=wide?Number(d.getBigUint64(p+16,le)):d.getUint32(p+12,le);need(offset,size);if(offset<8+n*step||ranges.some(([a,z])=>offset<z&&offset+size>a))throw Error('Mach-O: перекрывающиеся архитектуры');ranges.push([offset,offset+size]);architectures.push(parseMachO(b.subarray(offset,offset+size),depth+1))}return {format:'Mach-O Universal',architectures,sections:architectures.flatMap((a,i)=>a.sections.map(s=>({...s,architecture:i}))),notes:['Подписи и выполнение кода не проверялись.']}}
 if(![0xfeedface,0xfeedfacf,0xcefaedfe,0xcffaedfe].includes(magic))throw Error('Неизвестный Mach-O');const le=magic===0xcefaedfe||magic===0xcffaedfe,wide=magic===0xfeedfacf||magic===0xcffaedfe,header=wide?32:28;need(0,header);const u32=p=>{need(p,4);return d.getUint32(p,le)},u64=p=>{need(p,8);const v=Number(d.getBigUint64(p,le));if(!Number.isSafeInteger(v))throw Error('Mach-O: большое значение');return v},fixed=(p,n)=>{need(p,n);return new TextDecoder().decode(b.subarray(p,p+n)).replace(/\0.*$/,'')},n=u32(16),bytes=u32(20);if(n>4096)throw Error('Mach-O: лимит команд');need(header,bytes);let p=header;const sections=[],libraries=[],rpaths=[],segments=[];let encryption=null,signature=null,entryOffset=null;
 const string=(start,end)=>{if(start>=end)throw Error('Mach-O: смещение строки');let q=start;while(q<end&&b[q])q++;if(q===end)throw Error('Mach-O: незавершённая строка');return fixed(start,q-start)};
 for(let i=0;i<n;i++){need(p,8);const cmd=u32(p),size=u32(p+4),end=p+size;if(size<8||size%4||end>header+bytes)throw Error('Mach-O: некорректная команда');const requireSize=x=>{if(size<x)throw Error('Mach-O: короткая команда')};
 if(cmd===1||cmd===0x19){const is64=cmd===0x19,base=is64?72:56,step=is64?80:68;requireSize(base);const off=is64?u64(p+40):u32(p+32),len=is64?u64(p+48):u32(p+36),prot=u32(p+(is64?60:44)),count=u32(p+(is64?64:48));need(off,len);if(count>1024||base+count*step>size)throw Error('Mach-O: некорректные секции');segments.push({name:fixed(p+8,16),offset:off,size:len,protection:prot});for(let j=0;j<count;j++){const s=p+base+j*step,length=is64?u64(s+40):u32(s+36),offset=u32(s+(is64?48:40)),flags=u32(s+(is64?64:56)),zero=[1,12,18].includes(flags&255);if(!zero){need(offset,length);if(offset<off||offset+length>off+len)throw Error('Mach-O: секция вне сегмента')}sections.push({name:fixed(s,16),segment:fixed(s+16,16),offset,size:zero?0:length,virtualSize:length,executable:!!(prot&4),zeroFill:zero})}}
 else if([12,0x80000018,0x8000001f,0x20,0x80000023].includes(cmd)){requireSize(24);const off=u32(p+8);if(off<24)throw Error('Mach-O: имя библиотеки');libraries.push(string(p+off,end))}
 else if(cmd===0x8000001c){requireSize(12);const off=u32(p+8);if(off<12)throw Error('Mach-O: rpath');rpaths.push(string(p+off,end))}
 else if(cmd===0x21||cmd===0x2c){requireSize(cmd===0x2c?24:20);encryption={offset:u32(p+8),size:u32(p+12),id:u32(p+16)};need(encryption.offset,encryption.size)}
 else if(cmd===0x1d){requireSize(16);signature={offset:u32(p+8),size:u32(p+12)};need(signature.offset,signature.size)}
 else if(cmd===0x80000028){requireSize(24);entryOffset=u64(p+8)}p=end;
 }if(p!==header+bytes)throw Error('Mach-O: размер команд не совпадает');return {format:'Mach-O',bits:wide?64:32,cpu:u32(4),fileType:u32(12),sections,segments,libraries,rpaths,encryption,signature,entryOffset,notes:['Импорты: зависимости dylib; отдельные символы, подпись и выполнение кода не проверялись.',...(encryption?.id?['Mach-O зашифрован: содержимое секций недоступно для полного анализа.']:[])]};
}
