let lastRequest=0,chain=Promise.resolve();
const TTL=6*3600000;
function cache(){return new Promise((resolve,reject)=>{const r=indexedDB.open('aw-reputation-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('hashes',{keyPath:'cacheKey'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function cached(hash,value){const db=await cache();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('hashes',value?'readwrite':'readonly'),s=tx.objectStore('hashes'),r=value?s.put(value):s.get(hash);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
export function lookup(hash,key,provider,active=()=>true){const task=async()=>{if(!active())return {status:'disabled'};const cacheKey=provider+':'+hash;const old=await cached(cacheKey).catch(()=>null);if(old&&Date.now()-old.checkedAt<TTL)return {...old,cached:true};const wait=Math.max(0,16000-(Date.now()-lastRequest));if(wait)await new Promise(r=>setTimeout(r,wait));if(!active())return {status:'disabled'};lastRequest=Date.now();try{const r=await fetch('./api/reputation',{method:'POST',headers:{'Content-Type':'application/json',[provider==='VirusTotal'?'x-vt-key':'x-abuse-key']:key},body:JSON.stringify({sha256:hash,provider}),signal:AbortSignal.timeout(15000)});if(!r.ok)return {status:'unavailable',reason:r.status===429?'Лимит '+provider:r.status===401?'Проверьте API-ключ':'Сервис недоступен'};const v=await r.json();if(v.sha256!==hash||v.provider!==provider||!['detections','unknown','no_detections'].includes(v.status))return {status:'unavailable',reason:'Некорректный ответ'};await cached(cacheKey,{...v,cacheKey}).catch(()=>{});return v}catch{return {status:'unavailable',reason:'Нет связи с сервисом'}}};const next=chain.then(task,task);chain=next.catch(()=>{});return next}

export async function clearReputation(){const db=await cache();try{await new Promise((resolve,reject)=>{const tx=db.transaction('hashes','readwrite');tx.objectStore('hashes').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}}

export async function reputation(hash,keys,active=()=>true){const attempts=[];for(const [provider,key] of [['VirusTotal',keys.vt],['MalwareBazaar',keys.bazaar]]){if(!key||!active())continue;const result=await lookup(hash,key,provider,active);attempts.push({...result,provider});if(result.status==='detections')return {...result,attempts};}if(!attempts.length)return {status:'disabled',attempts};return {status:attempts.some(x=>x.status==='no_detections')?'no_detections':attempts.some(x=>x.status==='unknown')?'unknown':'unavailable',reason:'Настроенные сервисы не вернули вердикт',attempts};}
