import {boundedBytes} from './bounded-read.js';
const CACHE='aw-signatures-v2',KEY=new URL('./rules/active.json',import.meta.url).href;
const REMOTE='https://raw.githubusercontent.com/fomtimaz3-coder/antivirus-next/main/';
let current,pending;
async function verifiedText(root,f){if(!/^rules\/[a-zA-Z0-9_.-]+\.yar$/.test(f.path)||!/^[a-f0-9]{64}$/.test(f.sha256))throw Error('Некорректный файл правил');const response=await fetch(root+f.path,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Правила недоступны');const b=await boundedBytes(response,2*1024*1024);if(b.byteLength>2*1024*1024)throw Error('Превышен размер правил');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==f.sha256)throw Error('Контрольная сумма правил не совпала');return new TextDecoder().decode(b)}
async function loadPack(root,path){const r=await fetch(root+path,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Манифест базы недоступен');const manifest=JSON.parse(new TextDecoder().decode(await boundedBytes(r,256*1024)));if(![1,2].includes(manifest.schema)||!Array.isArray(manifest.files)||!manifest.files.length||manifest.files.length>20||!Array.isArray(manifest.shards||[])||(manifest.shards||[]).length>128)throw Error('Неизвестный формат базы');let source='';for(const f of manifest.files)source+='\n'+await verifiedText(root,f);return {manifest,source,sourceRoot:root}}
export async function getRules(){if(current)return current;if(pending)return pending;pending=(async()=>{try{const r=await (await caches.open(CACHE)).match(KEY);if(r)current=await r.json()}catch{}return current||updateRules()})();try{return await pending}finally{pending=null}}
export async function updateRules(){let next;try{next=await loadPack(REMOTE,'rules/manifest.json')}catch(e){if(current)throw e;next=await loadPack('./','rules/builtin.json')}
 const {yaraScan}=await import('./yara.js');const test=await yaraScan(new Blob(['anti-wiew rule compilation test']),next.source);if(test.error)throw Error(test.error);next.checkedAt=Date.now();current=next;try{const cache=await caches.open(CACHE);await cache.put(KEY,new Response(JSON.stringify(next),{headers:{'Content-Type':'application/json'}}));const keep=new Set((next.manifest.shards||[]).map(x=>new URL('./rules/cache-'+x.sha256,import.meta.url).href));for(const request of await cache.keys())if(request.url!==KEY&&!keep.has(request.url))await cache.delete(request)}catch{}return next}
export async function getShard(pack,shard){const key=new URL('./rules/cache-'+shard.sha256,import.meta.url).href;try{const r=await (await caches.open(CACHE)).match(key);if(r)return r.text()}catch{}const source=await verifiedText(pack.sourceRoot===REMOTE?REMOTE:'./',shard);try{await (await caches.open(CACHE)).put(key,new Response(source))}catch{}return source}
