import assert from 'node:assert/strict';import {createHash,randomBytes} from 'node:crypto';import fs from 'node:fs';import create from './vendor/yara.js';import {SHA256} from './sha256.js';import {hashIndex} from './bloom.js';import {entropy,staticAnalysis,parseDex,parsePE,parseELF} from './static-analysis.js';
for(const n of [0,1,55,56,63,64,65,1000,2097152,2097231]){const b=randomBytes(n);for(const stride of [17,65536]){const h=new SHA256();for(let i=0;i<n;i+=stride)h.update(b.subarray(i,i+stride));assert.equal(h.digest(),createHash('sha256').update(b).digest('hex'))}}
const source=fs.readdirSync(new URL('./rules/',import.meta.url)).filter(x=>x.endsWith('.yar')).map(x=>fs.readFileSync(new URL('./rules/'+x,import.meta.url),'utf8')).join('\n');
const wasmBinary=fs.readFileSync(new URL('./vendor/yara.wasm',import.meta.url));
// Browser transport adapter; actual native engine and whole scanner are exercised.
globalThis.Worker=class{postMessage({buffer,rules}){(async()=>{const m=await create({wasmBinary}),p=m._malloc(Math.max(1,buffer.byteLength));try{m.HEAPU8.set(new Uint8Array(buffer),p);const code=m.ccall('aw_scan','number',['number','number','string'],[p,buffer.byteLength,rules]);this.onmessage({data:code<0?{error:'YARA '+code}:{matches:m.UTF8ToString(m._aw_result()).trim().split('\n').filter(Boolean)}})}finally{m._free(p)}})().catch(e=>this.onerror?.(e))}terminate(){}};
let messages=[];globalThis.self={postMessage:m=>messages.push(m)};await import('./worker.js');async function scan(content,name='file.txt',database=[]){messages=[];const file=new Blob([content]);file.name=name;await self.onmessage({data:{file,id:'test',database,rulePack:{source,manifest:{version:'test'}}}});assert.equal(messages.at(-1).kind,'done',JSON.stringify(messages.at(-1)));return messages.at(-1).report}
const eicar='X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*';assert.equal((await scan(eicar)).findings[0].rule,'eicar');assert.equal((await scan('x'.repeat(2097140)+' '+eicar)).findings[0].rule,'eicar');assert.equal((await scan('hello')).findings.length,0);assert.equal((await scan('hello','test.txt',[{sha256:createHash('sha256').update('hello').digest('hex'),name:'Test hash'}])).findings[0].kind,'hash');assert.equal((await scan('')).bytesRead,0);assert((await scan('PK\x03\x04test','app.apk')).partial);
assert.equal(entropy(new Uint8Array(1000)),0);assert.equal(entropy(Uint8Array.from({length:256},(_,i)=>i)),8);const records=Array.from({length:2000},(_,i)=>({sha256:createHash('sha256').update(String(i)).digest('hex'),name:String(i)})),idx=hashIndex(records);for(const r of records)assert.equal(idx.find(r.sha256),r);assert.equal(idx.find('a'.repeat(64)),undefined);
assert.equal(staticAnalysis(new TextEncoder().encode('eval(atob("https://example.com"))'),'sample.js').findings.length,1);assert.equal(staticAnalysis(new TextEncoder().encode('eval(foo)'),'sample.js').findings.length,0);
assert.throws(()=>parseDex(new Uint8Array(112)));assert.throws(()=>parsePE(new Uint8Array(64)));assert.throws(()=>parseELF(new Uint8Array(52)));
const dex=new Uint8Array(112),dv=new DataView(dex.buffer);dex.set(new TextEncoder().encode('dex\n035\0'));dv.setUint32(32,112,true);dv.setUint32(36,112,true);dv.setUint32(40,0x12345678,true);assert.equal(parseDex(dex).methodCount,0);dv.setUint32(56,0xffffffff,true);assert.throws(()=>parseDex(dex));
const pe=new Uint8Array(1024),pv=new DataView(pe.buffer);pe.set([77,90]);pv.setUint32(60,64,true);pv.setUint32(64,0x4550,true);pv.setUint16(70,1,true);pv.setUint16(84,224,true);pv.setUint16(88,0x10b,true);pv.setUint32(148,512,true);pv.setUint32(180,16,true);const sec=312;pe.set(new TextEncoder().encode('.text'),sec);pv.setUint32(sec+8,512,true);pv.setUint32(sec+12,4096,true);pv.setUint32(sec+16,512,true);pv.setUint32(sec+20,512,true);pv.setUint32(sec+36,0x60000020,true);assert.equal(parsePE(pe).sections[0].executable,true);
console.log('PASS: real YARA community compilation/EICAR, boundary hashing, clean/no-match, hash lookup, empty/malformed files, entropy, Bloom no false negatives, script context, bounded DEX/PE/ELF.');
