import {inspectZip} from './archive.js';
import {SHA256} from './sha256.js';
const chunkSize=2*1024*1024;
const rules=[['SCRIPT-001','Загрузка и выполнение PowerShell',/powershell[^\r\n]{0,160}(?:-enc(?:odedcommand)?\b|downloadstring|iex\b)/i],['SCRIPT-002','Команда загрузки передаётся оболочке',/(?:curl|wget)[^\r\n]{0,180}\|\s*(?:ba)?sh\b/i],['SCRIPT-003','Декодирование строки с выполнением',/eval\s*\(\s*(?:atob|base64_decode)\s*\(/i]];
function format(b){const starts=(...a)=>a.every((n,i)=>b[i]===n);if(starts(0x50,0x4b,3,4)||starts(0x50,0x4b,5,6))return 'ZIP-контейнер';if(starts(0x4d,0x5a))return 'PE / DOS executable';if(starts(0x7f,0x45,0x4c,0x46))return 'ELF executable';if(starts(0x64,0x65,0x78,0x0a))return 'Android DEX';if(starts(0x25,0x50,0x44,0x46))return 'PDF';if(starts(0x89,0x50,0x4e,0x47,13,10,26,10))return 'PNG';if(starts(255,216,255))return 'JPEG';if(starts(0x1f,0x8b))return 'GZIP';if(starts(0x52,0x61,0x72,0x21))return 'RAR';if(starts(0x37,0x7a,0xbc,0xaf,0x27,0x1c))return '7z';if(starts(0xd0,0xcf,0x11,0xe0))return 'OLE document';return 'Не определён'}
self.onmessage=async({data:{file,id,database}})=>{const start=performance.now(),hash=new SHA256(),found=[],seen=new Set();let done=0,tail='',type='Не определён',last=0;const emit=(rule,title,kind,offset)=>{if(!seen.has(rule)){seen.add(rule);found.push({rule,title,kind,chunkOffset:offset})}};try{for(let offset=0;offset<file.size;offset+=chunkSize){const b=new Uint8Array(await file.slice(offset,offset+chunkSize).arrayBuffer());if(offset===0)type=format(b);hash.update(b);const text=tail+new TextDecoder('latin1').decode(b);if(text.includes('X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'))emit('EICAR','Обнаружен безвредный тестовый образец EICAR','test',offset);for(const [rule,title,re] of rules)if(re.test(text))emit(rule,title,'heuristic',offset);tail=text.slice(-512);done+=b.length;if(performance.now()-last>120||done===file.size){self.postMessage({kind:'progress',id,done,type,seconds:(performance.now()-start)/1000});last=performance.now()}}
let archive=null;
if(type==='ZIP-контейнер'){
 self.postMessage({kind:'progress',id,done,type,seconds:(performance.now()-start)/1000,phase:'archive'});
 try{archive=await inspectZip(file,(text,path)=>{const hits=[];if(text.includes('EICAR-STANDARD-ANTIVIRUS-TEST-FILE'))hits.push({rule:'EICAR-INNER',title:'Тестовая строка EICAR внутри '+path,kind:'test',path});for(const [rule,title,re] of rules)if(re.test(text))hits.push({rule,title,kind:'heuristic',path});return hits},progress=>self.postMessage({kind:'progress',id,done,type,phase:'archive',seconds:(performance.now()-start)/1000,...progress}));for(const entry of archive.entries){for(const f of entry.findings)found.push(f);const hit=database.find(x=>x.sha256===entry.sha256);if(hit)found.push({rule:'HASH-DB-INNER',title:hit.name,kind:'hash',path:entry.name})}}catch(e){archive={entries:[],total:0,scanned:0,skipped:0,expandedBytes:0,limitations:[e.message],error:e.message}}
}
const sha256=hash.digest();const match=database.find(x=>x.sha256===sha256);if(match)emit('HASH-DB',match.name,'hash',0);const ext=file.name.split('.').pop().toLowerCase();if((type==='PE / DOS executable'||type==='ELF executable')&&/^(jpg|jpeg|png|pdf|txt|mp3|mp4)$/.test(ext))emit('FORMAT-001','Исполняемый файл скрыт за другим расширением','heuristic',0);
const limitations=['Нет актуальной встроенной базы вредоносного ПО.','Статический анализ не доказывает безопасность и не проверяет поведение файла.','Эвристики анализируют только видимые байтовые строки; обфускация и кодировки могут скрыть признаки.'];if(/ZIP|GZIP|RAR|7z|PDF|OLE|DEX|executable/.test(type)||/^(apk|aab|zip|rar|7z|gz|tar|docx|xlsx|pptx|doc|xls|pdf)$/.test(ext))limitations.push('Подписи APK, поведение кода и макросы не проверены. Для ZIP выполняется ограниченная распаковка одного уровня; другие контейнеры не распаковываются.');if(type==='Не определён')limitations.push('Формат не распознан. Выполнены только хеширование и поиск байтовых признаков.');
if(archive){limitations.push(...archive.limitations);if(archive.skipped)limitations.push('Пропущено записей архива: '+archive.skipped)}
self.postMessage({kind:'done',id,report:{archive,apk:archive?.apk||null,partial:!!archive&&(!!archive.error||archive.skipped>0||archive.limitations.length>0),id,name:file.name,size:file.size,mime:file.type||'Не указан',type,sha256,created:new Date().toISOString(),durationMs:Math.round(performance.now()-start),bytesRead:done,engine:'AW-2.0',databaseEntries:database.length,findings:found,limitations,status:found.some(x=>x.kind==='hash')?'Совпадение с базой':found.some(x=>x.kind==='test')?'Обнаружен тест EICAR':found.length?'Подозрительные признаки':'Совпадений не найдено',coverage:'Ограниченный статический анализ',log:['Файл прочитан частями по 2 МиБ','Вычислен SHA-256 всех байтов','Проверены EICAR, 3 эвристики скриптов и маскировка исполняемого файла',`Сопоставлено записей SHA-256: ${database.length}`]}})}catch(e){self.postMessage({kind:'error',id,error:String(e.message||e),done})}};
