
rule elf_babuk_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2024-10-31"
        version = "1"
        description = "Detects elf.babuk."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.babuk"
        malpedia_rule_date = "20241030"
        malpedia_hash = "26e26953c49c8efafbf72a38076855d578e0a2e4"
        malpedia_version = "20241030"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 658b0d00000000 8b89fcffffff 3b6108 7678 83ec14 8b442418 8b4c241c }
            // n = 7, score = 200
            //   658b0d00000000       | mov                 ecx, dword ptr gs:[0]
            //   8b89fcffffff         | mov                 ecx, dword ptr [ecx - 4]
            //   3b6108               | cmp                 esp, dword ptr [ecx + 8]
            //   7678                 | jbe                 0x7a
            //   83ec14               | sub                 esp, 0x14
            //   8b442418             | mov                 eax, dword ptr [esp + 0x18]
            //   8b4c241c             | mov                 ecx, dword ptr [esp + 0x1c]

        $sequence_1 = { 8b4c2438 890f 8b542444 89570c 8b1d???????? 85db }
            // n = 6, score = 200
            //   8b4c2438             | mov                 ecx, dword ptr [esp + 0x38]
            //   890f                 | mov                 dword ptr [edi], ecx
            //   8b542444             | mov                 edx, dword ptr [esp + 0x44]
            //   89570c               | mov                 dword ptr [edi + 0xc], edx
            //   8b1d????????         |                     
            //   85db                 | test                ebx, ebx

        $sequence_2 = { e8???????? 8b44240c 89442410 8b4c2418 890c24 e8???????? 8b442420 }
            // n = 7, score = 200
            //   e8????????           |                     
            //   8b44240c             | mov                 eax, dword ptr [esp + 0xc]
            //   89442410             | mov                 dword ptr [esp + 0x10], eax
            //   8b4c2418             | mov                 ecx, dword ptr [esp + 0x18]
            //   890c24               | mov                 dword ptr [esp], ecx
            //   e8????????           |                     
            //   8b442420             | mov                 eax, dword ptr [esp + 0x20]

        $sequence_3 = { e8???????? 8b442438 8b4804 90 8b492c 894c2420 e8???????? }
            // n = 7, score = 200
            //   e8????????           |                     
            //   8b442438             | mov                 eax, dword ptr [esp + 0x38]
            //   8b4804               | mov                 ecx, dword ptr [eax + 4]
            //   90                   | nop                 
            //   8b492c               | mov                 ecx, dword ptr [ecx + 0x2c]
            //   894c2420             | mov                 dword ptr [esp + 0x20], ecx
            //   e8????????           |                     

        $sequence_4 = { c3 658b1d00000000 8b9bfcffffff 8b5b18 8b5b70 8403 890424 }
            // n = 7, score = 200
            //   c3                   | ret                 
            //   658b1d00000000       | mov                 ebx, dword ptr gs:[0]
            //   8b9bfcffffff         | mov                 ebx, dword ptr [ebx - 4]
            //   8b5b18               | mov                 ebx, dword ptr [ebx + 0x18]
            //   8b5b70               | mov                 ebx, dword ptr [ebx + 0x70]
            //   8403                 | test                byte ptr [ebx], al
            //   890424               | mov                 dword ptr [esp], eax

        $sequence_5 = { 01d9 8b9c24a8010000 8bbc243c030000 01fb 11cd 8b8c248c010000 8b9c2464020000 }
            // n = 7, score = 200
            //   01d9                 | add                 ecx, ebx
            //   8b9c24a8010000       | mov                 ebx, dword ptr [esp + 0x1a8]
            //   8bbc243c030000       | mov                 edi, dword ptr [esp + 0x33c]
            //   01fb                 | add                 ebx, edi
            //   11cd                 | adc                 ebp, ecx
            //   8b8c248c010000       | mov                 ecx, dword ptr [esp + 0x18c]
            //   8b9c2464020000       | mov                 ebx, dword ptr [esp + 0x264]

        $sequence_6 = { 8b44244c 8b4c2440 31d2 eb06 8d5101 90 89f1 }
            // n = 7, score = 200
            //   8b44244c             | mov                 eax, dword ptr [esp + 0x4c]
            //   8b4c2440             | mov                 ecx, dword ptr [esp + 0x40]
            //   31d2                 | xor                 edx, edx
            //   eb06                 | jmp                 8
            //   8d5101               | lea                 edx, [ecx + 1]
            //   90                   | nop                 
            //   89f1                 | mov                 ecx, esi

        $sequence_7 = { 895328 8b9424b0000000 8b8c2490000000 01ca 33562c 89532c }
            // n = 6, score = 200
            //   895328               | mov                 dword ptr [ebx + 0x28], edx
            //   8b9424b0000000       | mov                 edx, dword ptr [esp + 0xb0]
            //   8b8c2490000000       | mov                 ecx, dword ptr [esp + 0x90]
            //   01ca                 | add                 edx, ecx
            //   33562c               | xor                 edx, dword ptr [esi + 0x2c]
            //   89532c               | mov                 dword ptr [ebx + 0x2c], edx

        $sequence_8 = { 8b5a40 39d8 0f85360f0000 89bc2408020000 81c4dc010000 c3 89c7 }
            // n = 7, score = 200
            //   8b5a40               | mov                 ebx, dword ptr [edx + 0x40]
            //   39d8                 | cmp                 eax, ebx
            //   0f85360f0000         | jne                 0xf3c
            //   89bc2408020000       | mov                 dword ptr [esp + 0x208], edi
            //   81c4dc010000         | add                 esp, 0x1dc
            //   c3                   | ret                 
            //   89c7                 | mov                 edi, eax

        $sequence_9 = { 8b4c2424 01ca 89942444050000 8b8c2490050000 c1e11a 898c2420050000 }
            // n = 6, score = 200
            //   8b4c2424             | mov                 ecx, dword ptr [esp + 0x24]
            //   01ca                 | add                 edx, ecx
            //   89942444050000       | mov                 dword ptr [esp + 0x544], edx
            //   8b8c2490050000       | mov                 ecx, dword ptr [esp + 0x590]
            //   c1e11a               | shl                 ecx, 0x1a
            //   898c2420050000       | mov                 dword ptr [esp + 0x520], ecx

    condition:
        7 of them and filesize < 4186112
}
rule elf_bashlite_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.bashlite."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.bashlite"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8b85ecefffff c9 c3 55 }
            // n = 4, score = 300
            //   8b85ecefffff         | lea                 ecx, [eax - 1]
            //   c9                   | jle                 0x16
            //   c3                   | movzx               eax, byte ptr [edi + 2]
            //   55                   | mov                 eax, ecx

        $sequence_1 = { 83f8ff 750c e8???????? 8b00 83f873 }
            // n = 5, score = 300
            //   83f8ff               | sub                 esp, 0xc
            //   750c                 | add                 esp, 8
            //   e8????????           |                     
            //   8b00                 | mov                 edx, eax
            //   83f873               | mov                 eax, dword ptr [ebp - 0x1c]

        $sequence_2 = { e8???????? c70016000000 e8???????? c70016000000 }
            // n = 4, score = 300
            //   e8????????           |                     
            //   c70016000000         | cmp                 eax, -1
            //   e8????????           |                     
            //   c70016000000         | jne                 0xd1

        $sequence_3 = { e8???????? 8945ec 837dec00 750b 8b45ec }
            // n = 5, score = 300
            //   e8????????           |                     
            //   8945ec               | mov                 dword ptr [esp + 4], 0x3a
            //   837dec00             | mov                 dword ptr [esp], eax
            //   750b                 | inc                 eax
            //   8b45ec               | mov                 dword ptr [esp], eax

        $sequence_4 = { 31c0 eb19 e8???????? c70016000000 }
            // n = 4, score = 300
            //   31c0                 | movzx               eax, byte ptr [ebp - 0x4c]
            //   eb19                 | mov                 byte ptr [ebp - 0x10], al
            //   e8????????           |                     
            //   c70016000000         | sub                 edx, eax

        $sequence_5 = { 31c0 eb19 e8???????? c70016000000 e8???????? c70016000000 83c8ff }
            // n = 7, score = 300
            //   31c0                 | movzx               eax, byte ptr [ebp - 0x1f]
            //   eb19                 | cmp                 al, 0x64
            //   e8????????           |                     
            //   c70016000000         | jne                 0x129e
            //   e8????????           |                     
            //   c70016000000         | movzx               eax, byte ptr [ebp - 0x1e]
            //   83c8ff               | cmp                 al, 0x3f

        $sequence_6 = { 8945ec 837dec00 750b 8b45ec }
            // n = 4, score = 300
            //   8945ec               | mov                 edi, eax
            //   837dec00             | jmp                 0xffffffaf
            //   750b                 | xor                 ebx, ebx
            //   8b45ec               | add                 esp, 0x10

        $sequence_7 = { 21d0 3345fc c9 c3 55 }
            // n = 5, score = 300
            //   21d0                 | movzx               eax, al
            //   3345fc               | jmp                 0x2a5
            //   c9                   | mov                 ecx, dword ptr [ebp - 4]
            //   c3                   | lea                 eax, [ebp - 0x1058]
            //   55                   | lea                 edx, [eax + 0x12]

        $sequence_8 = { 89c2 89d0 c1e81f 01d0 }
            // n = 4, score = 300
            //   89c2                 | test                al, al
            //   89d0                 | mov                 byte ptr [edx], al
            //   c1e81f               | cmp                 eax, -1
            //   01d0                 | cmovne              eax, dword ptr [esp + 0x2c]

        $sequence_9 = { 750c c785ecefffff01000000 eb0a c785ecefffff00000000 }
            // n = 4, score = 300
            //   750c                 | jne                 0xcf
            //   c785ecefffff01000000     | dec    ecx
            //   eb0a                 | mov                 eax, edx
            //   c785ecefffff00000000     | jmp    0xdf

    condition:
        7 of them and filesize < 2310144
}
rule elf_blackcat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.blackcat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.blackcat"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 721a b904000000 81fa???????? 720d b905000000 }
            // n = 5, score = 200
            //   721a                 | cmp                 ecx, 4
            //   b904000000           | jb                  0x3df
            //   81fa????????         |                     
            //   720d                 | dec                 esp
            //   b905000000           | mov                 esi, dword ptr [esp + 0x110]

        $sequence_1 = { 80d3ff 660f2ec8 19ed 660f2ec1 0fb6db 0f43dd 80fbff }
            // n = 7, score = 200
            //   80d3ff               | mov                 byte ptr [esp + 5], dl
            //   660f2ec8             | or                  dl, 0xf0
            //   19ed                 | mov                 byte ptr [esp + 8], dl
            //   660f2ec1             | mov                 edx, ecx
            //   0fb6db               | shr                 edx, 0xc
            //   0f43dd               | and                 dl, 0x3f
            //   80fbff               | or                  dl, 0x80

        $sequence_2 = { 83f801 0f95c0 20c8 0fb6e8 }
            // n = 4, score = 200
            //   83f801               | mov                 esi, dword ptr [esp + 0x30]
            //   0f95c0               | mov                 ebp, dword ptr [esp + 0x38]
            //   20c8                 | sub                 esp, 0x1c
            //   0fb6e8               | mov                 edx, dword ptr [esp + 0x38]

        $sequence_3 = { 7227 b803000000 81f9???????? 721a }
            // n = 4, score = 200
            //   7227                 | jae                 0x2bf
            //   b803000000           | jb                  0x4b
            //   81f9????????         |                     
            //   721a                 | lea                 edx, [ebx - 0xa732]

        $sequence_4 = { 5b c3 0f0b 0f0b }
            // n = 4, score = 200
            //   5b                   | lea                 esi, [ebx - 0x656b0]
            //   c3                   | pop                 ebx
            //   0f0b                 | mov                 eax, dword ptr [ebx + eax*4 - 0x50800]
            //   0f0b                 | add                 eax, ebx

        $sequence_5 = { 81fa???????? 721a b804000000 81fa???????? 720d }
            // n = 5, score = 200
            //   81fa????????         |                     
            //   721a                 | lea                 eax, [ecx - 9]
            //   b804000000           | cmp                 eax, 5
            //   81fa????????         |                     
            //   720d                 | jb                  0x199

        $sequence_6 = { b802000000 81f9???????? 7227 b803000000 81f9???????? 721a b804000000 }
            // n = 7, score = 200
            //   b802000000           | cmovne              ecx, esi
            //   81f9????????         |                     
            //   7227                 | xor                 esi, esi
            //   b803000000           | mov                 eax, 1
            //   81f9????????         |                     
            //   721a                 | mov                 edx, ebp
            //   b804000000           | jmp                 0x9f3

        $sequence_7 = { 80f965 7510 31c9 31c0 }
            // n = 4, score = 200
            //   80f965               | mov                 ebp, dword ptr [esp + 0x88]
            //   7510                 | dec                 eax
            //   31c9                 | mov                 edi, dword ptr [ebp]
            //   31c0                 | cmp                 cl, 3

        $sequence_8 = { b902000000 81fa???????? 7227 b903000000 81fa???????? 721a b904000000 }
            // n = 7, score = 200
            //   b902000000           | mov                 dword ptr [esp], ecx
            //   81fa????????         |                     
            //   7227                 | mov                 dword ptr [esp + 4], eax
            //   b903000000           | mov                 ecx, 1
            //   81fa????????         |                     
            //   721a                 | mov                 eax, dword ptr [esi + 0x40]
            //   b904000000           | mov                 dword ptr [eax + 0xd0], edi

        $sequence_9 = { 0f0b 90 90 90 90 53 }
            // n = 6, score = 200
            //   0f0b                 | mov                 ebx, dword ptr [esp + 0x10]
            //   90                   | ud2                 
            //   90                   | mov                 ebp, dword ptr [esp + 0x30]
            //   90                   | test                ebp, ebp
            //   90                   | je                  0x3b
            //   53                   | mov                 dword ptr [esp], ebp

    condition:
        7 of them and filesize < 8011776
}
rule elf_gobrat_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.gobrat."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.gobrat"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { e8???????? 488b542428 48895020 48895028 833d????????00 750b 488b542448 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   488b542428           | mov                 dword ptr [eax + 8], edx
            //   48895020             | dec                 eax
            //   48895028             | lea                 eax, [0x2769e0]
            //   833d????????00       |                     
            //   750b                 | dec                 eax
            //   488b542448           | mov                 ebx, dword ptr [esp + 0xe8]

        $sequence_1 = { eb15 8b7a18 488b842490000000 488b742468 e8???????? 488bac2480000000 4881c488000000 }
            // n = 7, score = 100
            //   eb15                 | mov                 edx, dword ptr [esp + 0x120]
            //   8b7a18               | dec                 ecx
            //   488b842490000000     | mov                 eax, eax
            //   488b742468           | dec                 ecx
            //   e8????????           |                     
            //   488bac2480000000     | mov                 ecx, ecx
            //   4881c488000000       | dec                 eax

        $sequence_2 = { f3410f1100 488d7001 488b8424b8000000 488b9c2498000000 4889f9 488b542430 4839f0 }
            // n = 7, score = 100
            //   f3410f1100           | dec                 esp
            //   488d7001             | mov                 esi, dword ptr [0xfffffff8]
            //   488b8424b8000000     | dec                 eax
            //   488b9c2498000000     | lea                 ecx, [esp + 0x160]
            //   4889f9               | dec                 eax
            //   488b542430           | mov                 dword ptr [esp + 8], ecx
            //   4839f0               | dec                 eax

        $sequence_3 = { eb0f 4889c7 488d156a5b1900 e8???????? 488d058e841000 488b5c2430 b907000000 }
            // n = 7, score = 100
            //   eb0f                 | dec                 eax
            //   4889c7               | mov                 dword ptr [esp + 0x60], eax
            //   488d156a5b1900       | dec                 esp
            //   e8????????           |                     
            //   488d058e841000       | mov                 dword ptr [esp + 0x90], ecx
            //   488b5c2430           | dec                 eax
            //   b907000000           | lea                 ebp, [esp + 0x50]

        $sequence_4 = { eb7b 488b742440 488d5601 488b7c2448 4839d7 7207 488b442468 }
            // n = 7, score = 100
            //   eb7b                 | dec                 eax
            //   488b742440           | lea                 ebx, [0x17cf22]
            //   488d5601             | mov                 ecx, 0xb
            //   488b7c2448           | dec                 eax
            //   4839d7               | mov                 edi, dword ptr [esp + 0x220]
            //   7207                 | dec                 eax
            //   488b442468           | mov                 esi, dword ptr [esp + 0x228]

        $sequence_5 = { ffd1 488b6c2428 4883c430 c3 4889442408 e8???????? 488b442408 }
            // n = 7, score = 100
            //   ffd1                 | mov                 ebx, eax
            //   488b6c2428           | dec                 eax
            //   4883c430             | lea                 eax, [0x12d244]
            //   c3                   | nop                 dword ptr [eax]
            //   4889442408           | nop                 
            //   e8????????           |                     
            //   488b442408           | dec                 eax

        $sequence_6 = { eb1d 4889f0 e8???????? 89c1 488b442458 6690 eb0a }
            // n = 7, score = 100
            //   eb1d                 | mov                 ebx, dword ptr [esp + 0x50]
            //   4889f0               | dec                 eax
            //   e8????????           |                     
            //   89c1                 | mov                 eax, edx
            //   488b442458           | mov                 eax, dword ptr [esp + 0x4c]
            //   6690                 | dec                 eax
            //   eb0a                 | lea                 edi, [eax + 8]

        $sequence_7 = { 8b0d???????? 85c9 7513 488d05db893600 488d1dcc8e0f00 e8???????? 488b0d???????? }
            // n = 7, score = 100
            //   8b0d????????         |                     
            //   85c9                 | dec                 eax
            //   7513                 | mov                 edx, dword ptr [esp + 0xd8]
            //   488d05db893600       | dec                 eax
            //   488d1dcc8e0f00       | mov                 edi, dword ptr [esp + 0x50]
            //   e8????????           |                     
            //   488b0d????????       |                     

        $sequence_8 = { eb0a 488b4c2450 488b5c2428 48895c2420 48894c2440 488d054bb72800 e8???????? }
            // n = 7, score = 100
            //   eb0a                 | sub                 esi, eax
            //   488b4c2450           | dec                 eax
            //   488b5c2428           | add                 esi, 9
            //   48895c2420           | dec                 eax
            //   48894c2440           | mov                 dword ptr [esp + 0x70], esi
            //   488d054bb72800       | dec                 ecx
            //   e8????????           |                     

        $sequence_9 = { ffd7 84c0 7532 488b742478 48ffc6 4c8b442470 4939f0 }
            // n = 7, score = 100
            //   ffd7                 | mov                 dword ptr [esp + 0x9c], edx
            //   84c0                 | dec                 eax
            //   7532                 | mov                 edx, 0x55e011e3
            //   488b742478           | int1                
            //   48ffc6               | jge                 0x1ce
            //   4c8b442470           | lodsb               al, byte ptr [esi]
            //   4939f0               | dec                 eax

    condition:
        7 of them and filesize < 12853248
}
rule elf_hideandseek_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.hideandseek."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.hideandseek"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 8b4510 0facd008 c1ea08 88410e 8b4510 88410f }
            // n = 6, score = 100
            //   8b4510               | mov                 eax, dword ptr [ebp + 0x10]
            //   0facd008             | shrd                eax, edx, 8
            //   c1ea08               | shr                 edx, 8
            //   88410e               | mov                 byte ptr [ecx + 0xe], al
            //   8b4510               | mov                 eax, dword ptr [ebp + 0x10]
            //   88410f               | mov                 byte ptr [ecx + 0xf], al

        $sequence_1 = { e8???????? c7863401000000000011 838e3001000020 c7864c01000015000000 e9???????? 83ec0c 56 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   c7863401000000000011     | mov    dword ptr [esi + 0x134], 0x11000000
            //   838e3001000020       | or                  dword ptr [esi + 0x130], 0x20
            //   c7864c01000015000000     | mov    dword ptr [esi + 0x14c], 0x15
            //   e9????????           |                     
            //   83ec0c               | sub                 esp, 0xc
            //   56                   | push                esi

        $sequence_2 = { 757c 50 55 56 56 e8???????? }
            // n = 6, score = 100
            //   757c                 | jne                 0x7e
            //   50                   | push                eax
            //   55                   | push                ebp
            //   56                   | push                esi
            //   56                   | push                esi
            //   e8????????           |                     

        $sequence_3 = { 59 8d0403 8d942450220000 52 50 e8???????? 891c24 }
            // n = 7, score = 100
            //   59                   | pop                 ecx
            //   8d0403               | lea                 eax, [ebx + eax]
            //   8d942450220000       | lea                 edx, [esp + 0x2250]
            //   52                   | push                edx
            //   50                   | push                eax
            //   e8????????           |                     
            //   891c24               | mov                 dword ptr [esp], ebx

        $sequence_4 = { e8???????? 83c410 85c0 7936 50 6800100000 8d7c2418 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   83c410               | add                 esp, 0x10
            //   85c0                 | test                eax, eax
            //   7936                 | jns                 0x38
            //   50                   | push                eax
            //   6800100000           | push                0x1000
            //   8d7c2418             | lea                 edi, [esp + 0x18]

        $sequence_5 = { 0f8896000000 8b1d???????? be10000000 833b00 782a 89f8 2b4304 }
            // n = 7, score = 100
            //   0f8896000000         | js                  0x9c
            //   8b1d????????         |                     
            //   be10000000           | mov                 esi, 0x10
            //   833b00               | cmp                 dword ptr [ebx], 0
            //   782a                 | js                  0x2c
            //   89f8                 | mov                 eax, edi
            //   2b4304               | sub                 eax, dword ptr [ebx + 4]

        $sequence_6 = { ff750c e8???????? 6800400000 56 53 ff7508 e8???????? }
            // n = 7, score = 100
            //   ff750c               | push                dword ptr [ebp + 0xc]
            //   e8????????           |                     
            //   6800400000           | push                0x4000
            //   56                   | push                esi
            //   53                   | push                ebx
            //   ff7508               | push                dword ptr [ebp + 8]
            //   e8????????           |                     

        $sequence_7 = { 894c2408 0facd608 89d7 895c240c 8b4c2408 8b5c240c }
            // n = 6, score = 100
            //   894c2408             | mov                 dword ptr [esp + 8], ecx
            //   0facd608             | shrd                esi, edx, 8
            //   89d7                 | mov                 edi, edx
            //   895c240c             | mov                 dword ptr [esp + 0xc], ebx
            //   8b4c2408             | mov                 ecx, dword ptr [esp + 8]
            //   8b5c240c             | mov                 ebx, dword ptr [esp + 0xc]

        $sequence_8 = { 53 6800100000 8d44242c 50 57 e8???????? 83c410 }
            // n = 7, score = 100
            //   53                   | push                ebx
            //   6800100000           | push                0x1000
            //   8d44242c             | lea                 eax, [esp + 0x2c]
            //   50                   | push                eax
            //   57                   | push                edi
            //   e8????????           |                     
            //   83c410               | add                 esp, 0x10

        $sequence_9 = { 339424dc000000 01c6 8b04edb8aa0508 8b8c24b4000000 11d7 0384ecf8000000 8b14edbcaa0508 }
            // n = 7, score = 100
            //   339424dc000000       | xor                 edx, dword ptr [esp + 0xdc]
            //   01c6                 | add                 esi, eax
            //   8b04edb8aa0508       | mov                 eax, dword ptr [ebp*8 + 0x805aab8]
            //   8b8c24b4000000       | mov                 ecx, dword ptr [esp + 0xb4]
            //   11d7                 | adc                 edi, edx
            //   0384ecf8000000       | add                 eax, dword ptr [esp + ebp*8 + 0xf8]
            //   8b14edbcaa0508       | mov                 edx, dword ptr [ebp*8 + 0x805aabc]

    condition:
        7 of them and filesize < 196608
}
rule elf_mirai_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.mirai."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.mirai"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { e9???????? e8???????? 66894314 e9???????? }
            // n = 4, score = 300
            //   e9????????           |                     
            //   e8????????           |                     
            //   66894314             | inc                 eax
            //   e9????????           |                     

        $sequence_1 = { 66c1e808 d0e8 8d04c0 28c2 }
            // n = 4, score = 300
            //   66c1e808             | add                 esp, 0x20
            //   d0e8                 | mov                 eax, dword ptr [esp + 0x64c]
            //   8d04c0               | push                ecx
            //   28c2                 | mov                 dword ptr [esp + 0x2c], eax

        $sequence_2 = { c1ea03 89d0 c1e005 01d0 89ca }
            // n = 5, score = 300
            //   c1ea03               | movzx               ecx, byte ptr [esp + 0x34]
            //   89d0                 | inc                 sp
            //   c1e005               | mov                 dword ptr [esp + 0x4a], edi
            //   01d0                 | inc                 esp
            //   89ca                 | movzx               edi, byte ptr [esp + 0x1f]

        $sequence_3 = { c1e005 01d0 89ca 29c2 }
            // n = 4, score = 300
            //   c1e005               | push                eax
            //   01d0                 | mov                 ebx, dword ptr [esp + 0x2c]
            //   89ca                 | push                ebx
            //   29c2                 | lea                 eax, [esp + 0x654]

        $sequence_4 = { 807c242b00 66894304 7406 66c743064000 c643092f }
            // n = 5, score = 300
            //   807c242b00           | cmp                 ax, 4
            //   66894304             | je                  0x7b
            //   7406                 | ror                 dx, 8
            //   66c743064000         | mov                 eax, edx
            //   c643092f             | ror                 ax, 8

        $sequence_5 = { c7433400000000 894330 c6433801 c6433903 }
            // n = 4, score = 300
            //   c7433400000000       | mov                 edi, esp
            //   894330               | inc                 ecx
            //   c6433801             | mov                 edi, eax
            //   c6433903             | mov                 edx, 7

        $sequence_6 = { c1ea03 89d0 c1e005 01d0 89ca 29c2 }
            // n = 6, score = 300
            //   c1ea03               | cmp                 byte ptr [eax + esi - 1], 0x2e
            //   89d0                 | jne                 0x193b
            //   c1e005               | mov                 byte ptr [edx], cl
            //   01d0                 | lea                 edx, [eax + ebx]
            //   89ca                 | xor                 ecx, ecx
            //   29c2                 | mov                 esi, dword ptr [esp + 0x40]

        $sequence_7 = { 66c1c808 807c242b00 66894304 7406 66c743064000 c643092f }
            // n = 6, score = 300
            //   66c1c808             | dec                 eax
            //   807c242b00           | mov                 esi, ebx
            //   66894304             | push                ebx
            //   7406                 | dec                 eax
            //   66c743064000         | mov                 ebx, ecx
            //   c643092f             | dec                 eax

        $sequence_8 = { 894330 c6433801 c6433903 c6433a03 c6433b06 }
            // n = 5, score = 300
            //   894330               | mov                 ebx, eax
            //   c6433801             | push                0xb
            //   c6433903             | push                eax
            //   c6433a03             | add                 esp, 0xc
            //   c6433b06             | mov                 ebx, eax

        $sequence_9 = { 6689432a e8???????? c7433400000000 894330 }
            // n = 4, score = 300
            //   6689432a             | lea                 ecx, [eax + 8]
            //   e8????????           |                     
            //   c7433400000000       | dec                 eax
            //   894330               | mov                 dword ptr [esp + 0x18], ecx

    condition:
        7 of them and filesize < 2228224
}
rule elf_nosedive_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.nosedive."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.nosedive"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { eb1c 8b1486 891487 48ffc0 4839c3 75f2 488d049d00000000 }
            // n = 7, score = 100
            //   eb1c                 | and                 eax, 2
            //   8b1486               | dec                 esp
            //   891487               | mov                 dword ptr [esp + 0x28], edi
            //   48ffc0               | cmp                 al, 1
            //   4839c3               | dec                 eax
            //   75f2                 | mov                 dword ptr [edx + ecx + 8], 0
            //   488d049d00000000     | dec                 eax

        $sequence_1 = { 8b12 83fa7f 0f869a000000 c1ea07 81fa001c0000 750a 4889b42480000000 }
            // n = 7, score = 100
            //   8b12                 | jne                 0x15a
            //   83fa7f               | dec                 esp
            //   0f869a000000         | mov                 esi, dword ptr [0x10]
            //   c1ea07               | dec                 eax
            //   81fa001c0000         | mov                 edi, dword ptr [ebx + 0x88]
            //   750a                 | dec                 esp
            //   4889b42480000000     | cmp                 dword ptr [edi + 8], esi

        $sequence_2 = { 85c0 746a 488d0d2f6c0400 ba6b000000 488d35d0680400 488d3dd5680400 e8???????? }
            // n = 7, score = 100
            //   85c0                 | jle                 0x3a1
            //   746a                 | dec                 esp
            //   488d0d2f6c0400       | mov                 ebp, dword ptr [esp + 8]
            //   ba6b000000           | dec                 eax
            //   488d35d0680400       | mov                 edx, dword ptr [esp]
            //   488d3dd5680400       | dec                 esp
            //   e8????????           |                     

        $sequence_3 = { e8???????? 488b7b10 e8???????? 48c7430801000000 ba08000000 48896b10 eb87 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   488b7b10             | je                  0x28a
            //   e8????????           |                     
            //   48c7430801000000     | dec                 esp
            //   ba08000000           | mov                 dword ptr [ebx + 0x108], esi
            //   48896b10             | dec                 esp
            //   eb87                 | mov                 edx, esi

        $sequence_4 = { eb1a 761a 4883ff02 7502 31ff 488d15c20d0e00 488d72f8 }
            // n = 7, score = 100
            //   eb1a                 | lea                 esp, [ebp - 0x28]
            //   761a                 | inc                 esp
            //   4883ff02             | mov                 eax, esi
            //   7502                 | pop                 ebx
            //   31ff                 | inc                 ecx
            //   488d15c20d0e00       | pop                 esp
            //   488d72f8             | inc                 ecx

        $sequence_5 = { 85c0 7460 4983c508 ebdf 4963ca 4889c7 4c89ce }
            // n = 7, score = 100
            //   85c0                 | mov                 ecx, ebx
            //   7460                 | dec                 esp
            //   4983c508             | mov                 esi, edi
            //   ebdf                 | dec                 esp
            //   4963ca               | mov                 edi, edi
            //   4889c7               | dec                 esp
            //   4c89ce               | lea                 eax, [esp + 0xd0]

        $sequence_6 = { 84c9 0f85b7000000 4180fd01 7429 31c0 4c8d0525950f00 4c89e2 }
            // n = 7, score = 100
            //   84c9                 | inc                 ecx
            //   0f85b7000000         | and                 esi, 7
            //   4180fd01             | mov                 edi, 1
            //   7429                 | test                al, al
            //   31c0                 | inc                 ecx
            //   4c8d0525950f00       | movzx               eax, byte ptr [eax + 0x14c]
            //   4c89e2               | jne                 0xb02

        $sequence_7 = { e8???????? 85c0 0f85bc020000 488b542438 488b742448 4c89ef e8???????? }
            // n = 7, score = 100
            //   e8????????           |                     
            //   85c0                 | mov                 eax, ebp
            //   0f85bc020000         | dec                 eax
            //   488b542438           | add                 ebx, 2
            //   488b742448           | dec                 esp
            //   4c89ef               | mov                 eax, ebp
            //   e8????????           |                     

        $sequence_8 = { 8b0d???????? 0fbae109 7333 85d2 790d 0fbae21e 488d058cb20100 }
            // n = 7, score = 100
            //   8b0d????????         |                     
            //   0fbae109             | test                ebp, ebp
            //   7333                 | mov                 eax, dword ptr [eax]
            //   85d2                 | cmp                 eax, 0xffff
            //   790d                 | jbe                 0x3b6
            //   0fbae21e             | shr                 eax, 7
            //   488d058cb20100       | cmp                 eax, 0x1c00

        $sequence_9 = { e9???????? 488d3d54b60b00 e8???????? 488d3dc4720c00 31c0 e8???????? 4c8d8c24b0010000 }
            // n = 7, score = 100
            //   e9????????           |                     
            //   488d3d54b60b00       | lea                 esp, [esp + 0x10]
            //   e8????????           |                     
            //   488d3dc4720c00       | mov                 edx, 0x10
            //   31c0                 | mov                 edi, ebp
            //   e8????????           |                     
            //   4c8d8c24b0010000     | mov                 ebp, eax

    condition:
        7 of them and filesize < 3268608
}
rule elf_persirai_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.persirai."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.persirai"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { 57 56 53 81ec0c280000 8bac2428280000 81bc2424280000ff270000 7779 }
            // n = 7, score = 100
            //   57                   | push                edi
            //   56                   | push                esi
            //   53                   | push                ebx
            //   81ec0c280000         | sub                 esp, 0x280c
            //   8bac2428280000       | mov                 ebp, dword ptr [esp + 0x2828]
            //   81bc2424280000ff270000     | cmp    dword ptr [esp + 0x2824], 0x27ff
            //   7779                 | ja                  0x7b

        $sequence_1 = { 31c0 81c4a4000000 5b 5e c3 89e2 }
            // n = 6, score = 100
            //   31c0                 | xor                 eax, eax
            //   81c4a4000000         | add                 esp, 0xa4
            //   5b                   | pop                 ebx
            //   5e                   | pop                 esi
            //   c3                   | ret                 
            //   89e2                 | mov                 edx, esp

        $sequence_2 = { 894108 c7411420000000 5b 5e c3 }
            // n = 5, score = 100
            //   894108               | mov                 dword ptr [ecx + 8], eax
            //   c7411420000000       | mov                 dword ptr [ecx + 0x14], 0x20
            //   5b                   | pop                 ebx
            //   5e                   | pop                 esi
            //   c3                   | ret                 

        $sequence_3 = { 57 56 53 83ec0c 89c7 be???????? }
            // n = 6, score = 100
            //   57                   | push                edi
            //   56                   | push                esi
            //   53                   | push                ebx
            //   83ec0c               | sub                 esp, 0xc
            //   89c7                 | mov                 edi, eax
            //   be????????           |                     

        $sequence_4 = { 53 e8???????? 66c744241c0200 83c410 eb16 66833b02 7410 }
            // n = 7, score = 100
            //   53                   | push                ebx
            //   e8????????           |                     
            //   66c744241c0200       | mov                 word ptr [esp + 0x1c], 2
            //   83c410               | add                 esp, 0x10
            //   eb16                 | jmp                 0x18
            //   66833b02             | cmp                 word ptr [ebx], 2
            //   7410                 | je                  0x12

        $sequence_5 = { 56 53 83ec0c 89c7 be???????? }
            // n = 5, score = 100
            //   56                   | push                esi
            //   53                   | push                ebx
            //   83ec0c               | sub                 esp, 0xc
            //   89c7                 | mov                 edi, eax
            //   be????????           |                     

        $sequence_6 = { 83ec10 8b5c2418 ff74241c 53 e8???????? 83c410 83caff }
            // n = 7, score = 100
            //   83ec10               | sub                 esp, 0x10
            //   8b5c2418             | mov                 ebx, dword ptr [esp + 0x18]
            //   ff74241c             | push                dword ptr [esp + 0x1c]
            //   53                   | push                ebx
            //   e8????????           |                     
            //   83c410               | add                 esp, 0x10
            //   83caff               | or                  edx, 0xffffffff

        $sequence_7 = { 89c3 8b8424b4000000 8944241c 8b8424b8000000 89442420 8b8424bc000000 89442424 }
            // n = 7, score = 100
            //   89c3                 | mov                 ebx, eax
            //   8b8424b4000000       | mov                 eax, dword ptr [esp + 0xb4]
            //   8944241c             | mov                 dword ptr [esp + 0x1c], eax
            //   8b8424b8000000       | mov                 eax, dword ptr [esp + 0xb8]
            //   89442420             | mov                 dword ptr [esp + 0x20], eax
            //   8b8424bc000000       | mov                 eax, dword ptr [esp + 0xbc]
            //   89442424             | mov                 dword ptr [esp + 0x24], eax

        $sequence_8 = { 8b542418 89d0 83c41c c3 56 53 83c8ff }
            // n = 7, score = 100
            //   8b542418             | mov                 edx, dword ptr [esp + 0x18]
            //   89d0                 | mov                 eax, edx
            //   83c41c               | add                 esp, 0x1c
            //   c3                   | ret                 
            //   56                   | push                esi
            //   53                   | push                ebx
            //   83c8ff               | or                  eax, 0xffffffff

        $sequence_9 = { d1fa 0fb68292810508 c3 55 57 56 53 }
            // n = 7, score = 100
            //   d1fa                 | sar                 edx, 1
            //   0fb68292810508       | movzx               eax, byte ptr [edx + 0x8058192]
            //   c3                   | ret                 
            //   55                   | push                ebp
            //   57                   | push                edi
            //   56                   | push                esi
            //   53                   | push                ebx

    condition:
        7 of them and filesize < 229376
}
rule elf_satori_auto {

    meta:
        author = "Felix Bilstein - yara-signator at cocacoding dot com"
        date = "2026-05-04"
        version = "1"
        description = "Detects elf.satori."
        info = "autogenerated rule brought to you by yara-signator"
        tool = "yara-signator v0.6.0"
        signator_config = "callsandjumps;datarefs;binvalue"
        malpedia_reference = "https://malpedia.caad.fkie.fraunhofer.de/details/elf.satori"
        malpedia_rule_date = "20260422"
        malpedia_hash = "a182e35da64e6d71cb55f125c4d4225196523f14"
        malpedia_version = "20260504"
        malpedia_license = "CC BY-SA 4.0"
        malpedia_sharing = "TLP:WHITE"

    /* DISCLAIMER
     * The strings used in this rule have been automatically selected from the
     * disassembly of memory dumps and unpacked files, using YARA-Signator.
     * The code and documentation is published here:
     * https://github.com/fxb-cocacoding/yara-signator
     * As Malpedia is used as data source, please note that for a given
     * number of families, only single samples are documented.
     * This likely impacts the degree of generalization these rules will offer.
     * Take the described generation method also into consideration when you
     * apply the rules in your use cases and assign them confidence levels.
     */


    strings:
        $sequence_0 = { ff442438 66c1c808 66894214 8b442420 66c1c808 66894102 8d4508 }
            // n = 7, score = 100
            //   ff442438             | inc                 dword ptr [esp + 0x38]
            //   66c1c808             | ror                 ax, 8
            //   66894214             | mov                 word ptr [edx + 0x14], ax
            //   8b442420             | mov                 eax, dword ptr [esp + 0x20]
            //   66c1c808             | ror                 ax, 8
            //   66894102             | mov                 word ptr [ecx + 2], ax
            //   8d4508               | lea                 eax, [ebp + 8]

        $sequence_1 = { 6a01 6a0e 56 53 e8???????? 88442456 }
            // n = 6, score = 100
            //   6a01                 | push                1
            //   6a0e                 | push                0xe
            //   56                   | push                esi
            //   53                   | push                ebx
            //   e8????????           |                     
            //   88442456             | mov                 byte ptr [esp + 0x56], al

        $sequence_2 = { 0fa39484b8080000 0f92c0 84c0 0f84ad110000 80bd3604000000 7492 81bd2404000000040000 }
            // n = 7, score = 100
            //   0fa39484b8080000     | bt                  dword ptr [esp + eax*4 + 0x8b8], edx
            //   0f92c0               | setb                al
            //   84c0                 | test                al, al
            //   0f84ad110000         | je                  0x11b3
            //   80bd3604000000       | cmp                 byte ptr [ebp + 0x436], 0
            //   7492                 | je                  0xffffff94
            //   81bd2404000000040000     | cmp    dword ptr [ebp + 0x424], 0x400

        $sequence_3 = { 8d5001 895304 8b54241c 66c1c808 0fb7c0 894704 8b441108 }
            // n = 7, score = 100
            //   8d5001               | lea                 edx, [eax + 1]
            //   895304               | mov                 dword ptr [ebx + 4], edx
            //   8b54241c             | mov                 edx, dword ptr [esp + 0x1c]
            //   66c1c808             | ror                 ax, 8
            //   0fb7c0               | movzx               eax, ax
            //   894704               | mov                 dword ptr [edi + 4], eax
            //   8b441108             | mov                 eax, dword ptr [ecx + edx + 8]

        $sequence_4 = { 034510 83e1fc 8d3c0e 897ddc 39c7 7628 6a00 }
            // n = 7, score = 100
            //   034510               | add                 eax, dword ptr [ebp + 0x10]
            //   83e1fc               | and                 ecx, 0xfffffffc
            //   8d3c0e               | lea                 edi, [esi + ecx]
            //   897ddc               | mov                 dword ptr [ebp - 0x24], edi
            //   39c7                 | cmp                 edi, eax
            //   7628                 | jbe                 0x2a
            //   6a00                 | push                0

        $sequence_5 = { fc 8dbc2438090000 31c0 ab ab ab ab }
            // n = 7, score = 100
            //   fc                   | cld                 
            //   8dbc2438090000       | lea                 edi, [esp + 0x938]
            //   31c0                 | xor                 eax, eax
            //   ab                   | stosd               dword ptr es:[edi], eax
            //   ab                   | stosd               dword ptr es:[edi], eax
            //   ab                   | stosd               dword ptr es:[edi], eax
            //   ab                   | stosd               dword ptr es:[edi], eax

        $sequence_6 = { 56 6a06 6a03 6a02 e8???????? 83c410 83f8ff }
            // n = 7, score = 100
            //   56                   | push                esi
            //   6a06                 | push                6
            //   6a03                 | push                3
            //   6a02                 | push                2
            //   e8????????           |                     
            //   83c410               | add                 esp, 0x10
            //   83f8ff               | cmp                 eax, -1

        $sequence_7 = { e8???????? 01c5 83c410 e9???????? 80f978 750f 8b442408 }
            // n = 7, score = 100
            //   e8????????           |                     
            //   01c5                 | add                 ebp, eax
            //   83c410               | add                 esp, 0x10
            //   e9????????           |                     
            //   80f978               | cmp                 cl, 0x78
            //   750f                 | jne                 0x11
            //   8b442408             | mov                 eax, dword ptr [esp + 8]

        $sequence_8 = { 31db 42 83fe06 7f08 8a4202 41 84c0 }
            // n = 7, score = 100
            //   31db                 | xor                 ebx, ebx
            //   42                   | inc                 edx
            //   83fe06               | cmp                 esi, 6
            //   7f08                 | jg                  0xa
            //   8a4202               | mov                 al, byte ptr [edx + 2]
            //   41                   | inc                 ecx
            //   84c0                 | test                al, al

        $sequence_9 = { 83ec0c 57 e8???????? 83c410 83ec0c ff742414 e8???????? }
            // n = 7, score = 100
            //   83ec0c               | sub                 esp, 0xc
            //   57                   | push                edi
            //   e8????????           |                     
            //   83c410               | add                 esp, 0x10
            //   83ec0c               | sub                 esp, 0xc
            //   ff742414             | push                dword ptr [esp + 0x14]
            //   e8????????           |                     

    condition:
        7 of them and filesize < 122880
}